name: clipboard_watcher
description: This plugin allows Flutter desktop apps to watch clipboard changes.
version: 0.1.3
homepage: https://github.com/leanflutter/clipboard_watcher

platforms:
  linux:
  macos:
  windows:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: ClipboardWatcherPlugin
      macos:
        pluginClass: ClipboardWatcherPlugin
      windows:
        pluginClass: ClipboardWatcherPlugin
      ios:
        pluginClass: ClipboardWatcherPlugin
